### ISSUE TITLE
No Drop Crashing

### ISSUE THREAD

**Issue by Nuclearmayhem** [O-n-y/oxy.mods#26] opened 2020-09-20 04:40 UTC
Since the update I've had issues with it crashing about every 2 cycles with the following error.

  [DebugConsole][1]: Error[Exception]: NullReferenceException
UnityEngine.Object.get_name () (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
Ony.OxygenNotIncluded.NoDrop.DropManager.Drop (UnityEngine.GameObject gameObject, System.Int32 cell, UnityEngine.GameObject item) (at <bff86e731c9f4735ab49c1f0709129c8>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <bff86e731c9f4735ab49c1f0709129c8>:0)

  [DebugConsole][1]: Error[Exception]: NullReferenceException
UnityEngine.Object.get_name () (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
Ony.OxygenNotIncluded.NoDrop.DropManager.Drop (UnityEngine.GameObject gameObject, System.Int32 cell, UnityEngine.GameObject item) (at <bff86e731c9f4735ab49c1f0709129c8>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <bff86e731c9f4735ab49c1f0709129c8>:0)

**Comment by survaaki** [comment] 2020-09-20 07:29
UnityEngine.Object.get_name () (at <a35d771e78bd4d75a6f3aedeaad4d1ed>:0)
Ony.OxygenNotIncluded.NoDrop.DropManager.Drop (UnityEngine.GameObject gameObject, System.Int32 cell, UnityEngine.GameObject item) (at <bff86e731c9f4735ab49c1f0709129c8>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <bff86e731c9f4735ab49c1f0709129c8>:0)

Intermittent but regular occurrence sometimes 2 crashes within minutes sometimes only every half hour

Impractical to replicate using this mod only as it would just take far to long playing some random game to try hunt the bug.

Adding to this report as it seems to be the same bug.

Attachment has a number of mods activated in the save

[Vaccum Miners.zip](https://github.com/O-n-y/oxy.mods/files/5251262/Vaccum.Miners.zip)

**Comment by O-n-y** [comment] 2020-09-21 10:28
@Nuclearmayhem, @survaaki 
Please check if you have the same issue without additional mods, so I can confirm it is not related to some particular mod which need tp be tested out.

if it happen to be only with mods, yout list of mods will be helpful as well to compare which you one you can in common.

@survaaki thnk you for the save file, I will check it out.

**Comment by O-n-y** [comment] 2020-09-21 11:34
@survaaki i was able to reproduce issue on your save file, will be checking it out

**Comment by O-n-y** [comment] 2020-09-21 12:32
@survaaki PM me in Discord

**Comment by O-n-y** [comment] 2020-09-21 15:50
should be fixed in   1.0.7.65 r

**Comment by survaaki** [comment] 2020-09-22 07:08
Very much appreciated, thank you!

**Closed** 2020-09-22 11:17 UTC
Labels: No Drop, bug, confirmed

**Comment by Nuclearmayhem** [comment] 2020-09-22 23:55
Thank you and much appreciated that it's been fixed.
