### ISSUE TITLE
[No Drop] Dupes dropping items on ladder

### ISSUE THREAD

**Issue by robinderat** [O-n-y/oxy.mods#178] opened 2024-08-12 13:59 UTC
Duplicate of #174 as that one got closed.

From my experiments it seems that duplicants will drop items to their left once they reach solid ground, rather than on the tile they are standing on. 

Game version 623711
Mod version 1.3.0.4

Created a simple example of this happening in this save file
[Colony.zip](https://github.com/user-attachments/files/16587871/Colony.zip)

**Comment by O-n-y** [comment] 2024-08-20 07:29
Make sure you do _not have other mods enabled_ (mine other mods are fine) to ensure this is not caused by other mod.

To manage mods  i recommend to use my other mod:
MPOrganizer: https://steamcommunity.com/sharedfiles/filedetails/?id=3284635963
Save current mods list as preset (so you could easily restore it later).
Disable other mods (except mine) and check if the issue persist.

**Comment by robinderat** [comment] 2024-08-20 17:24
I believe I already did this when I created the savefile, but just to be sure I just disabled my other mods again and the issue still persists

**Comment by Baleine82** [comment] 2024-08-20 22:56
I just noticed the same info. I'm not sure I had the latest version of the mod (but I guess it should have been, since the last version was released a year ago… still, I won't claim it was), and I had other mods.
The pattern of my base was this :
```
--¦---
- ¦   
-  ¦  
-  ¦
```

`-` = wall
`¦` = ladder

Maybe something confused the duplicants, but as soon as they finished catching their breath, they were going on top of the ladder, dropped their load, and buzzed of on their merry way.

**Comment by O-n-y** [comment] 2024-08-21 05:56
I am asking because some of the mods, in particular as far as i remember FastTrack - could change the game in the way, it could cause bugs. So it is important to test without third-party mods.

**Comment by Baleine82** [comment] 2024-08-21 20:12
I reproduced it on the save, with only `Mod Manager` and `No Drop` activated.

from the crude graph where I described the part of the base where I saw the drop, here is what happens precisely

```
--¦---
- x    <- Duplicant is catching its breath here   
-  ¦  
-  ¦
```

```
--¦---
- ¦   
-  x    <- Duplicant drop its load when reaching this place
-  ¦
```

Here is a save : [The Regrettable Paradise Cycle 13.zip](https://github.com/user-attachments/files/16698209/The.Regrettable.Paradise.Cycle.13.zip)
The orders are already given, the base is small, you should see it happen if you look at the bottom of the base, where a reservoir for polluted water is under construction

**Comment by robinderat** [comment] 2024-08-22 15:00
This counts for my savefile as well. Everything has been set up so you should see it happen within 10 seconds of starting the save

**Comment by O-n-y** [comment] 2024-08-26 16:18
Will be fixed on next release.
I will also add a "Debug" option to settings, if turned on you will see debug tooltip and game will be paused on item drop, so it will be easy to see where is the drop position exactly.

**Closed** 2024-08-27 04:42 UTC
Labels: No Drop, bug, confirmed, fixed on next release build
