### ISSUE TITLE
No Drop v1.3.0.4 ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by bleistift-zwei** [O-n-y/oxy.mods#155] opened 2024-04-01 21:16 UTC
After several hours of stable gameplay my game crashed with the following message:

```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.RemoveAt (System.Int32 index) (at <b69d74babc594991a6033f935c4f5292>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <b69d74babc594991a6033f935c4f5292>:0)

Build: U51-600112-V
```

At the time of the crash I have not done anything noteworthy, so unfortunately I don’t have a reproduction. I also played again from the last autosave and couldn’t reproduce the issue, so I doubt the savegame is of any use to you.

However, my duplicants are currently dying. My guess is that this is related to a duplicant dying while they were carrying something in an unsafe place.

**Comment by MilanDierick** [comment] 2024-08-19 21:35
:+1:

**Comment by O-n-y** [comment] 2024-08-20 07:29
Make sure you do _not have other mods enabled_ (mine other mods are fine) to ensure this is not caused by other mod.

To manage mods  i recommend to use my other mod:
MPOrganizer: https://steamcommunity.com/sharedfiles/filedetails/?id=3284635963
Save current mods list as preset (so you could easily restore it later).
Disable other mods (except mine) and check if the issue persist.

**Comment by O-n-y** [comment] 2024-08-27 04:44
closing this one as no more information was provided

**Closed by O-n-y** 2024-08-27 04:44 UTC
Labels: No Drop, not yet confirmed, information requested
