### ISSUE TITLE
DSGM Dupes on rockets is not included in total count

### ISSUE THREAD

**Issue by jhammersholt** [O-n-y/oxy.mods#50] opened 2021-07-04 08:45 UTC
When you use "Option to print only care packages if you already have X alive Duplicants"

X alive duplicants do not count dupes on rockets in vanilla game without DLC

**Comment by O-n-y** [comment] 2021-07-04 09:35
Please provide save file where i can test this out, thank you

**Comment by jhammersholt** [comment] 2021-07-05 06:32
Sure - i use some mods so hopefully it will load for you

[The Leaky Dump.zip](https://github.com/O-n-y/oxy.mods/files/6762205/The.Leaky.Dump.zip)

**Comment by O-n-y** [comment] 2021-11-20 09:35
Hi!

I could not reproduce your issue.

Launched a rocker (so 1 duplicant in it).

We have 19 Duplicants in colony, even if in rocket we still at 19 count (top left screen of the game),
I have settings to print only care packages when we have 19 dups
[The Leaky Dump.zip](https://github.com/O-n-y/oxy.mods/files/7574274/The.Leaky.Dump.zip)

![2021-11-20_123130](https://user-images.githubusercontent.com/3432745/142721505-3d14650a-2aef-4f3d-a5b8-911ff13163f1.png)
![2021-11-20_123223](https://user-images.githubusercontent.com/3432745/142721506-b6b6f118-ebef-4f4a-a03a-9ca40f2a27b0.png)

If i need to do something else to reproduce the issue, please let me know.

**Comment by O-n-y** [comment] 2021-11-21 05:07
closing for now, will re-open, if new information will be provided

**Closed by O-n-y** 2021-11-21 05:07 UTC
Labels: @DGSM, information requested, not reproducible
