### ISSUE TITLE
[DGSM] Setting number of Positive Traits doesn't interact properly with Duplicant Configuration

### ISSUE THREAD

**Issue by ShadowKitty42** [O-n-y/oxy.mods#89] opened 2022-07-23 01:40 UTC
I haven't tested all of the combinations, primarily because I'm only interested in what I've set it to.... However, I set Positive Traits to 2 and started a new game. When trying to customize any of the starting dupes using the gear icon, there is only 1 positive trait listed in the window and clicking apply resets them to having 1 trait instead of 2. I would not be surprised if this affects negative traits also.

Edit: While playing around with other things I discovered I was slightly incorrect about this bug. Apparently this only occurs if you make the settings change, then immediately start a new game without restarting the game (the game doesn't prompt for a restart). If the setting is changed AND game is restarted, it has the correct number of traits.

**Comment by O-n-y** [comment] 2022-12-26 09:13
I could not reproduce this one, please provide screenshots with exact steps to cause this behaviour

**Comment by O-n-y** [comment] 2023-08-12 06:09
closing as not more information was provided

**Closed by O-n-y** 2023-08-12 06:09 UTC
Labels: @DGSM, not yet confirmed, information requested
