### ISSUE TITLE
NoDrop ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by PsychoDad9999** [O-n-y/oxy.mods#16] opened 2020-07-01 19:32 UTC
Hi,

I had the following crash a couple of times caused by your mod

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <dd00e5767eaa43ab96216cee53dbcbfe>:0)

I checked the code and there is an issue at the end of the FixedUpdate() Method where you use the List.RemoveAt function inside of a for-loop to remove the game objects. This will not work once an element has been removed, because the index of the game objects and the index of the list used in the loop will no longer match (either the wrong element is removed or an element outside of the range of the list is removed, which will cause the crash) 

Replacing the List.RemoveAt call with List.Remove should fix the issue. Hope that helps.

**Comment by O-n-y** [comment] 2020-07-01 19:45
provide information need for ticket: (How to report bug)
https://github.com/O-n-y/oxy.mods

**Comment by PsychoDad9999** [comment] 2020-07-01 19:57
Bug report relates to mod version 1.0.5.57

Let me know if you need additional information.

**Comment by PsychoDad9999** [comment] 2020-07-06 11:20
Just a quick update. 

I've patched your mod with the changes I've described in the first post and didn't had a single crash after that. I've played for 300 cycles, so it definitely fixed the crashing issues I had before.

**Comment by Tenelia** [comment] 2020-07-12 06:38
Issue still persists on my end. Hoping the fix will get pushed out. Anna's mods were crashing, so I had to remove them all...

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.List`1[T].RemoveAt (System.Int32 index) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () (at <dd00e5767eaa43ab96216cee53dbcbfe>:0)

**Comment by O-n-y** [comment] 2020-07-12 08:16
There was no update yet for this mod, so there is no point to report same issue multiple times, as it was already reported

**Comment by tsunamilx** [comment] 2020-09-17 03:26
> Just a quick update.
> 
> I've patched your mod with the changes I've described in the first post and didn't had a single crash after that. I've played for 300 cycles, so it definitely fixed the crashing issues I had before.

Hi @PsychoDad9999 would be much appreciated if you can share your patch here?

**Comment by O-n-y** [comment] 2020-09-17 06:33
Modifying code is not allowed, you have to wait for the new version to be release version to be pushed.

**Comment by O-n-y** [comment] 2020-09-17 07:40
Should be fixed in 1.0.6.60

**Comment by tsunamilx** [comment] 2020-09-17 14:07
Thanks a lot for the update, hoping you are well.
I just tried the new version, and just got another crash...
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Object.GetName(UnityEngine.Object)
  at UnityEngine.Object.get_name () [0x00001] in <a35d771e78bd4d75a6f3aedeaad4d1ed>:0 
  at Ony.OxygenNotIncluded.NoDrop.DropManager.Drop (UnityEngine.GameObject gameObject, System.Int32 cell, UnityEngine.GameObject item) [0x00017] in <bff86e731c9f4735ab49c1f0709129c8>:0 
  at Ony.OxygenNotIncluded.NoDrop.CarriedItemsComponent.FixedUpdate () [0x00190] in <bff86e731c9f4735ab49c1f0709129c8>:0

**Comment by O-n-y** [comment] 2020-09-17 16:47
have you checked you have exactly the last version? (version number in mod manager)
can you add a screenshot of the mod in the list?

**Comment by O-n-y** [comment] 2020-09-17 16:50
also the exception looks different, us it possible for you to provide save file where it can be replicated?

**Comment by tsunamilx** [comment] 2020-09-18 04:09
Yes, I am using the Mod Manger, and the version is 1.0.6.60. I am not sure a save file would help as I have tons of mods installed. I just got another try today, and haven't got any crash, so will update here if I got a crash again.

**Comment by O-n-y** [comment] 2020-09-18 06:34
from my tests, i didn't manage to replicate this issue currently

**Comment by O-n-y** [comment] 2020-09-18 11:55
From 5 hours stress on test map, i am still not able to reproduce this, it is possible some mod (maybe for speed or some other) cause this to happen.
So I am waiting for save file from you and instructions on how to reproduce it (including which mods should be activated for this to happen).

**Comment by tsunamilx** [comment] 2020-09-18 15:19
Never mind, I ran the game like 100 cycles, no crash, either it is super super rare issue or is caused by other mods. If no one else is reporting this issue, I would consider this as a good fix. 
Thanks a lot, really appreciated.

**Comment by O-n-y** [comment] 2020-09-18 15:53
i will close for now then

**Closed by O-n-y** 2020-09-18 15:53 UTC
Labels: No Drop, bug
