### ISSUE TITLE
Game freezes when trying to open Mod Manager

### ISSUE THREAD

**Issue by Emphasia** [O-n-y/oxy.mods#71] opened 2022-01-26 06:10 UTC
- OS: Windows 10 21H1 19043
- game version: U39-490405-VD
- Mod Manager version: 2.12.4.87
- mods enabled: only Mod Manager
- error description: 
	  1. enable mod manager
	  2. start game
	  3. Mod Manager shows all mods are up-to-date
	  4. click the "OK" button
	  4. click the "Module" button
	  5. Game freezes

**Comment by O-n-y** [comment] 2022-01-26 07:50
Attach your  `mods.json`
you can find it in the root of the /mods folder

**Comment by Emphasia** [comment] 2022-01-26 09:25
[mods.zip](https://github.com/O-n-y/oxy.mods/files/7940429/mods.zip)

**Comment by O-n-y** [comment] 2022-02-09 07:08
could not replicate yet.
`5. Game freezes` do you mean, you can't do anything and it is not responsible forever so you have to close it?
or do you mean there is a ~second lag and then all works again?

**Comment by Emphasia** [comment] 2022-02-09 07:58
> could not replicate yet. `5. Game freezes` do you mean, you can't do anything and it is not responsible forever so you have to close it? or do you mean there is a ~second lag and then all works again?

can't do anything and it is not responsible forever so I have to force close it

**Comment by O-n-y** [comment] 2022-02-09 12:52
this could be caused by some other mod. 
please do the following:
1) disable other mods (if you can't - unsub)
2) check if you still have this issue, if not - try to sub/enable mods one by one to know which one is causing this

**Comment by Emphasia** [comment] 2022-02-10 07:38
disable all mods -> everything works fine
enable only mod manager -> game freezes

**Comment by O-n-y** [comment] 2022-02-10 07:44
sadly i can't reproduce your issue
it should be something local, maybe some connection issue or firewall restrictions with api.steampowered.com etc
this is my only guess
also no one before reported anything like this before

**Comment by O-n-y** [comment] 2022-02-15 07:10
closing for now

**Closed by O-n-y** 2022-02-15 07:10 UTC
Labels: @ModManager, not yet confirmed, information requested
