### ISSUE TITLE
[DGSM - Duplicants Generation Settings Manager] REROLL buttons disappear

### ISSUE THREAD

**Issue by jpetays** [O-n-y/oxy.mods#64] opened 2021-12-25 10:34 UTC
REROLL buttons disappear if you close and then reopen "Select a Blueprint" dialog.

I disabled all mods except this mod DGSM - Duplicants Generation Settings Manager, mod manager and Bigger Camera Zoom Out.
I started a new game.
On cycle 12 I opened "Select a Blueprint" and closed it immediately.
Then I opened it again "REROLL" buttons have disappeared. There is only blank space where they were previously.
This should be easily reproducible.
before:
![oni_1before](https://user-images.githubusercontent.com/44498878/147383124-7ddf330e-481b-4878-b4a6-5f9cf8bd2443.gif)
after:
![oni_2after](https://user-images.githubusercontent.com/44498878/147383129-95da49a3-ba0d-4c06-8084-a71d9807f7b3.gif)

**Comment by O-n-y** [comment] 2022-02-08 07:59
Can you provide your DGSM settings? As i could not reproduce the issue on the last release build

**Comment by O-n-y** [comment] 2022-02-08 08:00
![GIF](https://user-images.githubusercontent.com/3432745/152943197-4399f3d3-9eb3-4142-8ac8-87688bded422.gif)

**Comment by jpetays** [comment] 2022-02-08 12:17
Here is my mods.json, mod_info.yaml and config.json (as text files).

I tested again few times a bit differently and on both times Reroll buttons disappeared as in my original post.
"Pause on ready to print" is only one that seems somehow related to this issue.

I have not touched DGSM settings so config.json should be in default values.
BTW, there is a typo in "DESCRIPTION": "All ptinted Duplicants will have this amount of interests"

As there is the workaround _not to close "Select a Blueprint" dialog after you have opened it first time_ and IMO there is no easy way to have better diagnostics you could just close this and maybe add a notice like:
Known issues: Under some rare mod combinations it is possible that Reroll buttons can disappear if you close "Select a Blueprint" dialog and then reopen it again.

[mods.json.txt](https://github.com/O-n-y/oxy.mods/files/8023600/mods.json.txt)
[mod_info.yaml.txt](https://github.com/O-n-y/oxy.mods/files/8023601/mod_info.yaml.txt)
[config.json.txt](https://github.com/O-n-y/oxy.mods/files/8023604/config.json.txt)

**Comment by O-n-y** [comment] 2022-02-09 06:59
`Pause on ready to print` - where this option from ?

**Comment by jpetays** [comment] 2022-02-09 09:26
[Pause on Ready To Print](https://steamcommunity.com/sharedfiles/filedetails/?id=2129768894) is a mod I have installed and IMO only one in addition to DGSM that is somehow related to Printing Pod.

**Comment by O-n-y** [comment] 2022-02-15 07:39
currently, i could not replicate this, but if I do, it will be fixed

**Closed** 2022-02-21 13:21 UTC
Labels: @DGSM, not reproducible

**Comment by O-n-y** [comment] 2022-02-21 15:39
please write me PM in discord
