### ISSUE TITLE
Seems to be a problem when reloading the research list from a saved game.

### ISSUE THREAD

**Issue by liushilive** [O-n-y/oxy.mods#46] opened 2021-05-17 08:43 UTC
Seems to be a problem when reloading the research list from a saved game.

I have the following research selected "Solid Fuel Combustion", "Hydrocarbon Combustion", "Solid Cargo", "Cryofuel Combustion", "Liquid and Gas Cargo", "Unique Cargo" all in that order.

When reloading from a save, the list reorders to directly by the tree order "Solid Fuel Combustion", "Hydrocarbon Combustion", "Cryofuel Combustion", then "Solid Cargo" all the way to "Unique Cargo".

This would seem to be incorrect behavior.

**Comment by O-n-y** [comment] 2021-05-17 08:44
please provide:
1. mod version you have installed
2. game save
3. mod settings you have (files)

**Comment by liushilive** [comment] 2021-05-17 08:59
![image](https://user-images.githubusercontent.com/13434707/118461445-44789b00-b730-11eb-970c-e0a3da22ef01.png)

![image](https://user-images.githubusercontent.com/13434707/118461798-9f11f700-b730-11eb-8331-9c6522628960.png)

config.json

```json
{
  "ConsoleEnabled": false,
  "ShowConfig": true,
  "AutoLoadPreset": true,
  "DisableResearchCompleteNotification": false,
  "ResearchQueue": [
    "FarmingTech",
    "FineDining",
    "Jobs",
    "AdvancedResearch",
    "BasicRefinement",
    "RefinedObjects",
    "Smelting"
  ],
  "MinZoom": 0.4,
  "MaxZoom": 1.0
}
```

![image](https://user-images.githubusercontent.com/13434707/118462266-121b6d80-b731-11eb-87ce-fd1f5a773b7a.png)

**Comment by O-n-y** [comment] 2021-05-17 12:04
attach game save file

**Comment by liushilive** [comment] 2021-05-18 01:58
[蓬勃的太空营.zip](https://github.com/O-n-y/oxy.mods/files/6497795/default.zip)

**Comment by liushilive** [comment] 2021-05-18 01:58
[蓬勃的太空营.zip](https://github.com/O-n-y/oxy.mods/files/6497798/default.zip)

**Comment by O-n-y** [comment] 2021-11-06 13:15
I could not reproduce from game save you gave me (it is start of the game)
please provide save file where this could be reproduced (where you have research in order you said before:  "Solid Fuel Combustion", "Hydrocarbon Combustion", "Solid Cargo", "Cryofuel Combustion", "Liquid and Gas Cargo", "Unique Cargo" all in that order.)
also provide mod config file located in /mods/config/**_mod_steam_id_**/research_queue/**_colony_name_**

**Comment by O-n-y** [comment] 2021-11-06 13:15
i pretty sure i fixed this one before, not sure if this still actual.

**Comment by O-n-y** [comment] 2021-11-21 05:07
Closing up for now, will re-open, if new information will be provided

**Closed by O-n-y** 2021-11-21 05:07 UTC
Labels: ResearchManager, not yet confirmed, information requested
